repository:
  # See https://docs.github.com/en/rest/reference/repos#update-branch-protection for all available settings
  branches:
    - name: main
      protection:
        required_status_checks:
          strict: true
          contexts:
            - Test
