services:
  api-prod:
    container_name: nestjs-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - 3001:3001
    environment:
      - PORT=3001
      - NODE_ENV=production
