FROM node:24-alpine3.21
# Install pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Set working directory
WORKDIR /usr/src/app

# Copy root package files
COPY tsconfig.base.json pnpm-lock.yaml pnpm-workspace.yaml package.json ./

# Copy web app package.json
COPY apps/web/package.json ./apps/web/

# Install dependencies
RUN pnpm install --frozen-lockfile

# Copy web app source
COPY apps/web ./apps/web

# Set working directory to web app
WORKDIR /usr/src/app/apps/web

# Expose port
EXPOSE 3000

# Start development server
CMD ["pnpm", "dev"] 